# Generated by Django 5.2.17 on 2026-09-04 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("intent", models.CharField(blank=True, max_length=32, null=True)),
                ("summary_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                ("call_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(db_index=True, max_length=64)),
                ("arguments_json", models.JSONField(default=dict)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("result_ref", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="api.task",
                    ),
                ),
            ],
            options={
                "db_table": "tool_calls",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("role", models.CharField(db_index=True, max_length=16)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.task",
                    ),
                ),
                (
                    "tool_call",
                    models.ForeignKey(
                        blank=True,
                        db_column="tool_call_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="api.toolcall",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at", "message_id"],
            },
        ),
    ]
